TRANSPARENT = (0, 0, 0, 0)
WHITE = (255, 255, 255)
WHITISH = (224, 224, 224)
LIGHT_GRAY = (192, 192, 192)
GRAY = (128, 128, 128)
DARK_GRAY = (80, 80, 80)
DARK_DARK_GRAY = (32, 32, 32)
BLACK = (0, 0, 0)

ORIGIN = (0, 0)

TITLE = "SMZ3 Item Tracker"
ICON_PATH = ("images", "metroidicon.png")

FPS = 20

LARGE_BUTTON_SIZE = 64
SMALL_BUTTON_SIZE = 32
BUTTON_SPACING = 8

DIM_PERCENT = 75
HIGHLIGHT_BRIGHTEN = 12
HIGHLIGHT_BRIGHTEN_INACTIVE = 8
HIGHLIGHT_BRIGHTEN_STATUS_BAR = 6

WIN_WIDTH = 10 * (LARGE_BUTTON_SIZE + BUTTON_SPACING) + BUTTON_SPACING 
WIN_HEIGHT = 8 * (LARGE_BUTTON_SIZE + BUTTON_SPACING) + BUTTON_SPACING + SMALL_BUTTON_SIZE

TRACKER_FONT_NAME = "Consolas"
TRACKER_FONT_SIZE = 24
TRACKER_FONT_BORDER = 2
TRACKER_FONT_COLOR = WHITE
TRACKER_FONT_BORDER_COLOR = BLACK
TRIPLE_DIGIT_OFFSET = 6
INITIALS_FONT_SIZE = 18
LARGE_CHEST_FONT_SIZE = 36
SMALL_CHEST_FONT_SIZE = 16
CHEST_FONT_COLOR = BLACK
LARGE_CHEST_Y_OFFSET = 3
SMALL_CHEST_Y_OFFSET = 1

STATUS_BAR_FONT_PATH = ("fonts", "super-metroid.ttf")
STATUS_BAR_FONT_SIZE = 12
STATUS_BAR_BACKGROUND = DARK_DARK_GRAY
STATUS_BAR_POSITION = (0, WIN_HEIGHT - SMALL_BUTTON_SIZE)
STATUS_BAR_SIZE = (WIN_WIDTH, SMALL_BUTTON_SIZE)